### ISSUE TITLE
navbar not visible on mobile

### ISSUE THREAD

**Issue by crmackay** [GSBS-Bootstrappers/bootstrappers#1]
fyi @nickjhathaway 

the navbar collapses, but then is not visible on visible (tested in chrome dev tools and a real iPhone 6)

![image](https://cloud.githubusercontent.com/assets/3801862/9507153/4557a39a-4c1a-11e5-84f9-f463d948b77f.png)

seems to be only bioinfo.umassmed.edu/courses and /calendar....the courses pages themselves look okay

**Comment by nickjhathaway** [comment]
haha, yeah i removed some stuff that i thought just looked like some extra junk but apparently that was what made the nav bar on mobile devices whoops
